### ISSUE TITLE
New jsonProperty in Company model and get/set methods

### ISSUE THREAD

**Issue by tringuyen1401** [clearbit/clearbit-java#23]
According to this [blog post](https://blog.clearbit.com/estimated-revenue-and-company-hierarchy/), Clearbit has rolled out 2 new properties for company data. Can we add these two fields into the Company models and the setter/getter so we can extract it from the API?
Thank you

**Comment by davidlumley** [comment]
Hey @tringuyen1401 you sure can! If you can submit a PR we'll review it and help get it merged.
