### ISSUE TITLE
Publish Maven Artifacts

### ISSUE THREAD

**Issue by harlow** [clearbit/clearbit-java#7]
Ticket has been submitted (https://issues.sonatype.org/browse/OSSRH-18525) and now need to follow the remaining steps:

- [x] Deploy snapshot artifacts into repository https://oss.sonatype.org/content/repositories/snapshots
- [x] Deploy release artifacts into the staging repository https://oss.sonatype.org/service/local/staging/deploy/maven2
- [x] Promote staged artifacts into repository 'Releases'
- [x] Download snapshot and release artifacts from group https://oss.sonatype.org/content/groups/public
- [ ] Download snapshot, release and staged artifacts from staging group https://oss.sonatype.org/content/groups/staging

**Comment by harlow** [comment]
I've been following [these instructions](http://www.apache.org/dev/publishing-maven-artifacts.html) and getting stuck on staging a release.

http://www.apache.org/dev/publishing-maven-artifacts.html#staging-maven

```
code/clearbit/clearbit-java(master) $ mvn release:prepare -DdryRun=true
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building client 0.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-release-plugin:2.3.2:prepare (default-cli) @ client ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.884 s
[INFO] Finished at: 2015-11-09T15:27:21-08:00
[INFO] Final Memory: 11M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.3.2:prepare (default-cli) on project client: You don't have a SNAPSHOT project in the reactor projects list. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Any ideas on what needs to happen in the POM.xml in regards to `STAGING`?

**Comment by chadworth** [comment]
I think you want to commit a change which changes `<version>0.1</version>` in pom.xml to `<version>0.1-SNAPSHOT</version>` and then try running the `release:prepare` again.  The idea with Maven is that your version number always ends in `-SNAPSHOT` while you're developing. It knows if the version ends in `-SNAPSHOT` then the code can change. When you have a version without `-SNAPSHOT` then it's a released version where the code never changes. So the release process expects to change from `-SNAPSHOT` to a real version to release and then increments the version number and sets it back to `-SNAPSHOT` as the last stage of the release process.

**Comment by chadworth** [comment]
I just sent you one more PR that it'd be nice to get merged before publishing this to Maven https://github.com/clearbit/clearbit-java/pull/8

**Comment by chadworth** [comment]
@harlow ping. it'd be really nice to get this done

**Comment by chadworth** [comment]
@harlow ping. just a reminder. thanks!

**Comment by chadworth** [comment]
Hey Harlow, would you be able to give this a go?  Thanks!

**Comment by harlow** [comment]
Hey @chadworth do you published a package to Maven before? any chance we could pair on this to get it done quicker? Maybe do a screen share or something of the sort? I'm a bit stuck on next steps.

**Comment by harlow** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.337 s
[INFO] Finished at: 2016-01-09T08:10:22-08:00
[INFO] Final Memory: 12M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.3.2:perform (default-cli) on project client: Maven execution failed, exit code: '1' -> [Help 1]
```

**Comment by chadworth** [comment]
0.5 is in Maven now!

**Comment by harlow** [comment]
💪
